FROM node:22-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:alpine AS runtime
COPY --from=build /app/dist/marvi-client/browser /usr/share/nginx/html
COPY --from=deploy nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 4200
