// <auto-generated />
using System;
using System.Collections.Generic;
using Marvi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Marvi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Marvi.Domain.Auditing.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_name");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_audit_log_entries");

                    b.ToTable("audit_log_entries", (string)null);
                });

            modelBuilder.Entity("Marvi.Domain.Catalog.Deal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<List<Guid>>("CategoryIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("category_ids");

                    b.Property<int>("DiscountType")
                        .HasColumnType("integer")
                        .HasColumnName("discount_type");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("numeric")
                        .HasColumnName("discount_value");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<int>("MinQty")
                        .HasColumnType("integer")
                        .HasColumnName("min_qty");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.PrimitiveCollection<List<Guid>>("ProductIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("product_ids");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_deals");

                    b.ToTable("deals", (string)null);
                });

            modelBuilder.Entity("Marvi.Domain.Catalog.PricingTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_pricing_tiers");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasDatabaseName("ix_pricing_tiers_is_default")
                        .HasFilter("is_default = true");

                    b.ToTable("pricing_tiers", (string)null);
                });

            modelBuilder.Entity("Marvi.Domain.Catalog.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Marvi.Domain.Catalog.ProductPricing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("MinQty")
                        .HasColumnType("integer")
                        .HasColumnName("min_qty");

                    b.Property<Guid>("PricingTierId")
                        .HasColumnType("uuid")
                        .HasColumnName("pricing_tier_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_product_pricings");

                    b.HasIndex("PricingTierId")
                        .HasDatabaseName("ix_product_pricings_pricing_tier_id");

                    b.HasIndex("ProductId", "PricingTierId", "MinQty")
                        .IsUnique()
                        .HasDatabaseName("ix_product_pricings_product_id_pricing_tier_id_min_qty");

                    b.ToTable("product_pricings", (string)null);
                });

            modelBuilder.Entity("Marvi.Domain.Coverage.CoverageArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("PolygonGeoJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("polygon_geo_json");

                    b.Property<double?>("RadiusMiles")
                        .HasColumnType("double precision")
                        .HasColumnName("radius_miles");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_coverage_areas");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("ix_coverage_areas_warehouse_id");

                    b.ToTable("coverage_areas", (string)null);
                });

            modelBuilder.Entity("Marvi.Domain.Coverage.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_warehouses");

                    b.ToTable("warehouses", (string)null);
                });

            modelBuilder.Entity("Marvi.Domain.Identity.ClientAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BillingAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("billing_address");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_name");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("numeric")
                        .HasColumnName("credit_limit");

                    b.Property<Guid?>("PricingTierId")
                        .HasColumnType("uuid")
                        .HasColumnName("pricing_tier_id");

                    b.PrimitiveCollection<List<string>>("ShippingAddresses")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("shipping_addresses");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_client_accounts");

                    b.HasIndex("PricingTierId")
                        .HasDatabaseName("ix_client_accounts_pricing_tier_id");

                    b.ToTable("client_accounts", (string)null);
                });

            modelBuilder.Entity("Marvi.Domain.Identity.EmployeeAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Department")
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("employee_code");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hire_date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_employee_accounts");

                    b.ToTable("employee_accounts", (string)null);
                });

            modelBuilder.Entity("Marvi.Domain.Inventory.InventoryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("QtyOnHand")
                        .HasColumnType("integer")
                        .HasColumnName("qty_on_hand");

                    b.Property<int>("QtyReserved")
                        .HasColumnType("integer")
                        .HasColumnName("qty_reserved");

                    b.Property<int>("ReorderPoint")
                        .HasColumnType("integer")
                        .HasColumnName("reorder_point");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_records");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("ix_inventory_records_warehouse_id");

                    b.HasIndex("ProductId", "WarehouseId")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_records_product_id_warehouse_id");

                    b.ToTable("inventory_records", (string)null);
                });

            modelBuilder.Entity("Marvi.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_account_id");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("delivery_address");

                    b.Property<Guid?>("PlacedByEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("placed_by_employee_id");

                    b.Property<Guid?>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("total_amount");

                    b.Property<Guid?>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("ClientAccountId")
                        .HasDatabaseName("ix_orders_client_account_id");

                    b.HasIndex("PlacedByEmployeeId")
                        .HasDatabaseName("ix_orders_placed_by_employee_id");

                    b.HasIndex("QuoteId")
                        .HasDatabaseName("ix_orders_quote_id");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("ix_orders_warehouse_id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Marvi.Domain.Orders.OrderLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Qty")
                        .HasColumnType("integer")
                        .HasColumnName("qty");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_order_line_items");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_line_items_order_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_order_line_items_product_id");

                    b.ToTable("order_line_items", (string)null);
                });

            modelBuilder.Entity("Marvi.Domain.Quotes.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("PricedByEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("priced_by_employee_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_quotes");

                    b.HasIndex("ClientAccountId")
                        .HasDatabaseName("ix_quotes_client_account_id");

                    b.HasIndex("PricedByEmployeeId")
                        .HasDatabaseName("ix_quotes_priced_by_employee_id");

                    b.ToTable("quotes", (string)null);
                });

            modelBuilder.Entity("Marvi.Domain.Quotes.QuoteLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("FinalUnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("final_unit_price");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Qty")
                        .HasColumnType("integer")
                        .HasColumnName("qty");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<decimal?>("SuggestedUnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("suggested_unit_price");

                    b.HasKey("Id")
                        .HasName("pk_quote_line_items");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_quote_line_items_product_id");

                    b.HasIndex("QuoteId")
                        .HasDatabaseName("ix_quote_line_items_quote_id");

                    b.ToTable("quote_line_items", (string)null);
                });

            modelBuilder.Entity("Marvi.Infrastructure.Data.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Marvi.Domain.Catalog.ProductPricing", b =>
                {
                    b.HasOne("Marvi.Domain.Catalog.PricingTier", "PricingTier")
                        .WithMany("ProductPricings")
                        .HasForeignKey("PricingTierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_pricings_pricing_tiers_pricing_tier_id");

                    b.HasOne("Marvi.Domain.Catalog.Product", "Product")
                        .WithMany("ProductPricings")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_pricings_products_product_id");

                    b.Navigation("PricingTier");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Marvi.Domain.Coverage.CoverageArea", b =>
                {
                    b.HasOne("Marvi.Domain.Coverage.Warehouse", "Warehouse")
                        .WithMany("CoverageAreas")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_coverage_areas_warehouses_warehouse_id");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Marvi.Domain.Identity.ClientAccount", b =>
                {
                    b.HasOne("Marvi.Domain.Catalog.PricingTier", "PricingTier")
                        .WithMany()
                        .HasForeignKey("PricingTierId")
                        .HasConstraintName("fk_client_accounts_pricing_tiers_pricing_tier_id");

                    b.Navigation("PricingTier");
                });

            modelBuilder.Entity("Marvi.Domain.Inventory.InventoryRecord", b =>
                {
                    b.HasOne("Marvi.Domain.Catalog.Product", "Product")
                        .WithMany("InventoryRecords")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_records_products_product_id");

                    b.HasOne("Marvi.Domain.Coverage.Warehouse", "Warehouse")
                        .WithMany("InventoryRecords")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_records_warehouses_warehouse_id");

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Marvi.Domain.Orders.Order", b =>
                {
                    b.HasOne("Marvi.Domain.Identity.ClientAccount", "ClientAccount")
                        .WithMany("Orders")
                        .HasForeignKey("ClientAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orders_client_accounts_client_account_id");

                    b.HasOne("Marvi.Domain.Identity.EmployeeAccount", "PlacedByEmployee")
                        .WithMany()
                        .HasForeignKey("PlacedByEmployeeId")
                        .HasConstraintName("fk_orders_employee_accounts_placed_by_employee_id");

                    b.HasOne("Marvi.Domain.Quotes.Quote", "Quote")
                        .WithMany()
                        .HasForeignKey("QuoteId")
                        .HasConstraintName("fk_orders_quotes_quote_id");

                    b.HasOne("Marvi.Domain.Coverage.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .HasConstraintName("fk_orders_warehouses_warehouse_id");

                    b.Navigation("ClientAccount");

                    b.Navigation("PlacedByEmployee");

                    b.Navigation("Quote");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Marvi.Domain.Orders.OrderLineItem", b =>
                {
                    b.HasOne("Marvi.Domain.Orders.Order", "Order")
                        .WithMany("LineItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_line_items_orders_order_id");

                    b.HasOne("Marvi.Domain.Catalog.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_line_items_products_product_id");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Marvi.Domain.Quotes.Quote", b =>
                {
                    b.HasOne("Marvi.Domain.Identity.ClientAccount", "ClientAccount")
                        .WithMany("Quotes")
                        .HasForeignKey("ClientAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quotes_client_accounts_client_account_id");

                    b.HasOne("Marvi.Domain.Identity.EmployeeAccount", "PricedByEmployee")
                        .WithMany()
                        .HasForeignKey("PricedByEmployeeId")
                        .HasConstraintName("fk_quotes_employee_accounts_priced_by_employee_id");

                    b.Navigation("ClientAccount");

                    b.Navigation("PricedByEmployee");
                });

            modelBuilder.Entity("Marvi.Domain.Quotes.QuoteLineItem", b =>
                {
                    b.HasOne("Marvi.Domain.Catalog.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quote_line_items_products_product_id");

                    b.HasOne("Marvi.Domain.Quotes.Quote", "Quote")
                        .WithMany("LineItems")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quote_line_items_quotes_quote_id");

                    b.Navigation("Product");

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Marvi.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Marvi.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("Marvi.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Marvi.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("Marvi.Domain.Catalog.PricingTier", b =>
                {
                    b.Navigation("ProductPricings");
                });

            modelBuilder.Entity("Marvi.Domain.Catalog.Product", b =>
                {
                    b.Navigation("InventoryRecords");

                    b.Navigation("ProductPricings");
                });

            modelBuilder.Entity("Marvi.Domain.Coverage.Warehouse", b =>
                {
                    b.Navigation("CoverageAreas");

                    b.Navigation("InventoryRecords");
                });

            modelBuilder.Entity("Marvi.Domain.Identity.ClientAccount", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Quotes");
                });

            modelBuilder.Entity("Marvi.Domain.Orders.Order", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("Marvi.Domain.Quotes.Quote", b =>
                {
                    b.Navigation("LineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
